/** Demo data — TypeScript mirror of prototype-data.js D.*.
 * Used to seed SQLite on first run.
 *
 * Keep this file in sync with prototype-data.js. When the prototype changes,
 * regenerate this file from the prototype data.
 */

import type {
  Account,
  AccountSettings,
  AgentDraft,
  AgentSession,
  AgentTask,
  BundleConfig,
  CalendarEvent,
  Clip,
  Contact,
  ContactNote,
  Draft,
  FileItem,
  FollowUp,
  Label,
  Message,
  Notification,
  ScheduledSend,
  Shortcut,
  Snippet,
  Sticky,
  Task,
} from "../types";

const ACCT_SETTINGS_DEFAULT = (overrides: Partial<AccountSettings> = {}): AccountSettings => ({
  aliases: [],
  signature: "Best,\nEdwin",
  replyTo: "",
  defaultFrom: "",
  syncFolders: [
    { name: "INBOX", enabled: true },
    { name: "Sent", enabled: true },
    { name: "Drafts", enabled: true },
    { name: "Archive", enabled: true },
  ],
  syncFrequency: "15min",
  autoBcc: false,
  autoBccAddress: "",
  vacationResponder: { enabled: false, subject: "", body: "" },
  ...overrides,
});

export const DEMO_ACCOUNTS: Account[] = [
  {
    id: "gmail-w",
    type: "email",
    provider: "gmail",
    email: "edwin@sendpalm.com",
    label: "SendPalm 工作",
    displayName: "Edwin Hao",
    status: "connected",
    synced: 1247,
    total: 1247,
    privacy: "unified",
    color: "#ea4335",
    avatar: "S",
    lastSync: "刚刚",
    settings: ACCT_SETTINGS_DEFAULT({
      aliases: ["edwin@sendpalm.io", "e.hao@sendpalm.com"],
      signature: "Best,\nEdwin\nSendPalm",
      defaultFrom: "edwin@sendpalm.com",
      vacationResponder: {
        enabled: false,
        subject: "Out of office",
        body: "I am out of the office until Aug 5. For urgent matters please contact ops@sendpalm.com.",
      },
    }),
  },
  {
    id: "gmail-p",
    type: "email",
    provider: "gmail",
    email: "edwin.hao@gmail.com",
    label: "个人 Gmail",
    displayName: "Edwin",
    status: "connected",
    synced: 892,
    total: 892,
    privacy: "unified",
    color: "#ea4335",
    avatar: "G",
    lastSync: "5分钟前",
    settings: ACCT_SETTINGS_DEFAULT({
      signature: "— Edwin",
      defaultFrom: "edwin.hao@gmail.com",
      syncFrequency: "30min",
      autoBcc: true,
      autoBccAddress: "edwin@sendpalm.com",
    }),
  },
  {
    id: "outlook",
    type: "email",
    provider: "outlook",
    email: "edwin@sendpalm.com",
    label: "Outlook",
    displayName: "Edwin Hao",
    status: "error",
    error: "令牌过期，请重新认证",
    synced: 503,
    total: 503,
    privacy: "isolated",
    color: "#0078d4",
    avatar: "O",
    lastSync: "3天前",
    settings: ACCT_SETTINGS_DEFAULT({
      aliases: ["edwin.hao@outlook.com"],
      signature: "Best regards,\nEdwin",
      defaultFrom: "edwin@sendpalm.com",
      syncFrequency: "1h",
    }),
  },
  {
    id: "slack",
    type: "im",
    provider: "slack",
    workspace: "sendpalm",
    label: "Slack · sendpalm",
    displayName: "Slack · sendpalm",
    status: "syncing",
    synced: 128,
    total: 340,
    privacy: "unified",
    color: "#4a154b",
    avatar: "S",
    lastSync: "同步中",
  },
  {
    id: "wechat",
    type: "im",
    provider: "wechat",
    label: "微信",
    displayName: "微信",
    status: "connected",
    synced: 156,
    total: 156,
    privacy: "isolated",
    color: "#22c55e",
    avatar: "微",
    lastSync: "1小时前",
  },
  {
    id: "calendar",
    type: "calendar",
    provider: "google",
    label: "Google 日历",
    displayName: "Google 日历",
    status: "connected",
    synced: 24,
    total: 24,
    privacy: "unified",
    color: "#a78bfa",
    avatar: "日",
    lastSync: "2小时前",
  },
];

const mkContact = (overrides: Partial<Contact> & { id: string }): Contact => ({
  firstName: "",
  lastName: "",
  nickname: "",
  name: "",
  company: "",
  title: "",
  emails: [],
  phones: [],
  stage: "explore",
  labels: [],
  topics: [],
  notes: "",
  avatar: "",
  photo: "",
  health: 0,
  sc: 0,
  scC: "#8e8e93",
  scL: "",
  lc: "",
  grp: "",
  trd: "stable",
  pattern: "",
  accounts: [],
  stageHistory: [],
  firstContact: "2024-01-01",
  milestones: [],
  merged: false,
  blocked: false,
  notify: true,
  firstSeen: false,
  screened: true,
  defaultBucket: "imbox",
  autoLabel: [],
  recycling: false,
  ch: [],
  ...overrides,
});

export const DEMO_CONTACTS: Contact[] = [
  mkContact({
    id: "zl", firstName: "磊", lastName: "张", name: "张磊",
    company: "华为", title: "战略合作总监",
    emails: [{ value: "zhanglei@huawei.com", label: "work" }],
    phones: [{ value: "+86 138****1234", label: "work" }],
    stage: "active", health: 94, sc: 94, scC: "#34c759", scL: "活跃", lc: "2天前",
    grp: "active", trd: "up",
    pattern: "通常周二上午发邮件，平均回复 4.2h",
    accounts: ["gmail-w", "wechat"],
    stageHistory: [{ stage: "build", date: "2026-01-15" }, { stage: "active", date: "2026-03-01" }],
    firstContact: "2026-01-10",
    milestones: ["合同签署 2026-03-15", "Q2评审 2026-06-20"],
    avatar: "https://picsum.photos/seed/zhanglei/128/128",
    photo: "https://picsum.photos/seed/zhanglei/128/128",
    topics: ["Q4合同", "付款条款", "交付物定义"],
    notes: "Q4 合同推进中，付款条款已调整到 30-40-30。张磊对交付物验收标准比较关注，需提前准备 3 份附件。",
    merged: true, ch: ["Gmail", "Calendar", "WeChat"],
  }),
  mkContact({
    id: "cx", firstName: "欣", lastName: "陈", name: "陈欣",
    company: "字节跳动", title: "战略合作经理",
    emails: [{ value: "chen.xin@bytedance.com", label: "work" }],
    phones: [{ value: "+86 139****5678", label: "work" }],
    stage: "build", health: 87, sc: 87, scC: "#34c759", scL: "活跃", lc: "今天",
    grp: "active", trd: "up",
    pattern: "通常下午回复，平均回复 2.1h",
    accounts: ["gmail-w", "slack"],
    stageHistory: [{ stage: "explore", date: "2026-04-01" }, { stage: "build", date: "2026-05-15" }],
    firstContact: "2026-04-01",
    milestones: ["Q3合作启动 2026-05"],
    avatar: "https://picsum.photos/seed/chenxin/128/128",
    photo: "https://picsum.photos/seed/chenxin/128/128",
    topics: ["Q3回顾", "Q4规划", "API升级"],
    notes: "Q4 规划基本对齐，整合阶段提前两周需要技术评估。陈欣 Slack 响应很快，紧急事项优先走 Slack。",
    merged: true, ch: ["Gmail", "Slack"],
  }),
  mkContact({
    id: "wy", firstName: "洋", lastName: "王", name: "王洋",
    company: "阿里巴巴", title: "采购总监",
    emails: [{ value: "wang.yang@alibaba-inc.com", label: "personal" }],
    phones: [{ value: "+86 137****9012", label: "work" }],
    stage: "cold", health: 34, sc: 34, scC: "#ff9500", scL: "需跟进", lc: "7天前",
    grp: "risk", trd: "dn",
    pattern: "以前回复很快，近期明显变慢",
    accounts: ["gmail-p", "gmail-w"],
    stageHistory: [{ stage: "active", date: "2026-01-01" }, { stage: "cold", date: "2026-06-01" }],
    firstContact: "2025-09-01",
    milestones: ["Q3合同 2025-12"],
    avatar: "https://picsum.photos/seed/wangyang/128/128",
    photo: "https://picsum.photos/seed/wangyang/128/128",
    topics: ["Q4提案", "预算规划"],
    notes: "45 天未回复 Q4 提案。王总以前回复很快，近期明显变慢，可能内部预算未定。建议下周电话跟进。",
    merged: true, ch: ["Gmail"],
  }),
  mkContact({
    id: "lc", firstName: "晨", lastName: "李", name: "李晨",
    company: "腾讯", title: "技术VP",
    emails: [{ value: "lichen@tencent.com", label: "work" }],
    phones: [{ value: "+86 136****3456", label: "work" }],
    stage: "cold", health: 18, sc: 18, scC: "#ff3b30", scL: "已冷淡", lc: "14天前",
    grp: "cold", trd: "dn",
    pattern: "之前每月1次沟通，已中断2个月",
    accounts: ["gmail-w", "wechat"],
    stageHistory: [{ stage: "active", date: "2025-06-01" }, { stage: "cold", date: "2026-05-01" }],
    firstContact: "2025-03-01",
    milestones: ["AI项目启动 2025-06", "一期交付 2026-04"],
    avatar: "https://picsum.photos/seed/lichen/128/128",
    photo: "https://picsum.photos/seed/lichen/128/128",
    topics: ["技术合作", "AI方案"],
    notes: "已冷淡 62 天。二期立项 busy，建议 2 周后发一份 AI 行业洞察重新激活，不要直接推销。",
    merged: true, ch: ["Gmail", "WeChat"],
  }),
  mkContact({
    id: "sj", firstName: "静", lastName: "孙", name: "孙静",
    company: "美团", title: "产品负责人",
    emails: [{ value: "sunjing@meituan.com", label: "work" }],
    phones: [{ value: "+86 135****7890", label: "work" }],
    stage: "maintain", health: 82, sc: 82, scC: "#34c759", scL: "活跃", lc: "5天前",
    grp: "active", trd: "up",
    pattern: "Slack响应比邮件快，平均2h",
    accounts: ["gmail-w", "slack"],
    stageHistory: [{ stage: "build", date: "2025-11-01" }, { stage: "active", date: "2026-02-01" }, { stage: "maintain", date: "2026-05-01" }],
    firstContact: "2025-11-01",
    milestones: ["项目Alpha上线 2026-04"],
    avatar: "https://picsum.photos/seed/sunjing/128/128",
    photo: "https://picsum.photos/seed/sunjing/128/128",
    topics: ["项目部署", "测试计划"],
    notes: "Alpha 已上线，周五部署前需 review 测试计划。孙静 Slack 响应比邮件快，发票 #1024 已收到，付款期限 30 天。",
    merged: true, ch: ["Gmail", "Slack"],
  }),
  mkContact({
    id: "yy", firstName: "雨", lastName: "杨", name: "杨雨",
    company: "小红书", title: "商务合作",
    emails: [{ value: "yang.yu@xiaohongshu.com", label: "work" }],
    phones: [{ value: "+86 134****2345", label: "work" }],
    stage: "build", health: 76, sc: 76, scC: "#34c759", scL: "活跃", lc: "3天前",
    grp: "active", trd: "stable",
    pattern: "每周1-2次邮件往来",
    accounts: ["gmail-w"],
    stageHistory: [{ stage: "explore", date: "2026-05-01" }, { stage: "build", date: "2026-06-01" }],
    firstContact: "2026-05-01",
    avatar: "https://picsum.photos/seed/yangyu/128/128",
    photo: "https://picsum.photos/seed/yangyu/128/128",
    topics: ["联名活动", "创意方案"],
    notes: "联名活动方案内部已过，创意方向 OK，预算需要再压一压。准备一份更轻量级的资源方案。",
    merged: true, ch: ["Gmail"],
  }),
  mkContact({
    id: "xm", firstName: "明", lastName: "谢", name: "谢明",
    company: "京东", title: "供应链总监",
    emails: [{ value: "xieming@jd.com", label: "work" }],
    phones: [{ value: "+86 133****6789", label: "work" }],
    stage: "maintain", health: 91, sc: 91, scC: "#34c759", scL: "活跃", lc: "1天前",
    grp: "active", trd: "up",
    pattern: "固定每周一沟通",
    accounts: ["gmail-w"],
    stageHistory: [{ stage: "active", date: "2025-08-01" }, { stage: "maintain", date: "2026-03-01" }],
    firstContact: "2025-05-01",
    milestones: ["供应链框架签约 2025-09"],
    avatar: "https://picsum.photos/seed/xieming/128/128",
    photo: "https://picsum.photos/seed/xieming/128/128",
    topics: ["供应链评估", "Q3报告"],
    notes: "Q3 供应链评估整体 A-，几个小问题项已标注。明天评审会需带 Q3 报告和 PPT，谢明已发邮箱。",
    merged: true, ch: ["Gmail", "Calendar"],
  }),
  mkContact({
    id: "lh", firstName: "华", lastName: "刘", name: "刘华",
    company: "百度", title: "AI合作负责人",
    emails: [{ value: "liuhua@baidu.com", label: "personal" }],
    phones: [{ value: "+86 132****0123", label: "work" }],
    stage: "cold", health: 45, sc: 45, scC: "#ff9500", scL: "需跟进", lc: "14天前",
    grp: "risk", trd: "dn",
    pattern: "项目一期完成后沟通频率下降",
    accounts: ["gmail-p"],
    stageHistory: [{ stage: "build", date: "2025-10-01" }, { stage: "active", date: "2026-01-01" }, { stage: "cold", date: "2026-06-06" }],
    firstContact: "2025-10-01",
    milestones: ["AI项目一期启动 2026-01", "一期验收 2026-06"],
    avatar: "https://picsum.photos/seed/liuhua/128/128",
    photo: "https://picsum.photos/seed/liuhua/128/128",
    topics: ["AI项目", "一期验收"],
    notes: "一期已验收，二期预算在走流程，预计下月初有结果。不要频繁催促，保持月度节奏。",
    merged: true, ch: ["Gmail", "WeChat"],
  }),
  mkContact({
    id: "zw", firstName: "薇", lastName: "赵", name: "赵薇",
    company: "网易", title: "市场总监",
    emails: [{ value: "zhaowei@163.com", label: "work" }],
    phones: [{ value: "+86 131****4567", label: "work" }],
    stage: "active", health: 68, sc: 68, scC: "#34c759", scL: "活跃", lc: "1周前",
    grp: "active", trd: "stable",
    pattern: "每月集中沟通2-3次",
    accounts: ["gmail-w", "slack"],
    stageHistory: [{ stage: "build", date: "2026-02-01" }, { stage: "active", date: "2026-04-01" }],
    firstContact: "2026-02-01",
    milestones: ["Q2联合活动 2026-04"],
    avatar: "https://picsum.photos/seed/zhaowei/128/128",
    photo: "https://picsum.photos/seed/zhaowei/128/128",
    topics: ["Q3市场活动", "资源支持"],
    notes: "Q3 活动排期节奏 OK，设计资源下周三到位，文案还需两天。下周一过终稿，需预留半天 review。",
    merged: true, ch: ["Gmail", "Slack"],
  }),
  mkContact({
    id: "nw", firstName: "Frontend", lastName: "Weekly", name: "Frontend Weekly",
    company: "Frontend Weekly",
    emails: [{ value: "editor@frontendweekly.com", label: "personal" }],
    phones: [],
    stage: "explore", health: 0, sc: 0, scC: "#8e8e93", scL: "", lc: "昨天",
    pattern: "每周二发送",
    accounts: ["gmail-p"],
    firstContact: "2025-01-01",
    avatar: "https://picsum.photos/seed/frontendweekly/128/128",
    photo: "https://picsum.photos/seed/frontendweekly/128/128",
    notes: "技术周刊订阅。",
    defaultBucket: "feed", ch: ["Gmail"],
  }),
  mkContact({
    id: "aws", firstName: "Amazon", lastName: "Web Services", name: "Amazon Web Services",
    company: "AWS",
    emails: [{ value: "billing@aws.com", label: "work" }],
    phones: [],
    stage: "explore", health: 0, sc: 0, scC: "#8e8e93", scL: "", lc: "2天前",
    pattern: "月度账单与系统通知",
    accounts: ["gmail-w"],
    firstContact: "2024-06-01",
    avatar: "https://picsum.photos/seed/awsbilling/128/128",
    photo: "https://picsum.photos/seed/awsbilling/128/128",
    notes: "AWS 账单与系统通知。",
    defaultBucket: "paperTrail", ch: ["Gmail"],
  }),
  mkContact({
    id: "hr", firstName: "HR", lastName: "小助手", name: "HR 小助手",
    company: "SendPalm",
    emails: [{ value: "hr@sendpalm.com", label: "work" }],
    phones: [],
    stage: "explore", health: 0, sc: 0, scC: "#8e8e93", scL: "", lc: "今天",
    pattern: "内部通知与考勤提醒",
    accounts: ["gmail-w"],
    firstContact: "2025-03-01",
    avatar: "https://picsum.photos/seed/hrassistant/128/128",
    photo: "https://picsum.photos/seed/hrassistant/128/128",
    notes: "公司内部 HR 系统通知。",
    defaultBucket: "paperTrail", ch: ["Gmail"],
  }),
  mkContact({
    id: "mj", firstName: "杰", lastName: "马", name: "马杰",
    company: "自由职业", title: "独立开发者",
    emails: [{ value: "majie@gmail.com", label: "personal" }],
    phones: [{ value: "+86 150****8888", label: "work" }],
    stage: "maintain", health: 72, sc: 72, scC: "#34c759", scL: "活跃", lc: "3天前",
    grp: "active", trd: "stable",
    pattern: "不定期联系",
    accounts: ["gmail-p"],
    stageHistory: [{ stage: "active", date: "2025-06-01" }, { stage: "maintain", date: "2026-01-01" }],
    firstContact: "2020-03-15",
    avatar: "https://picsum.photos/seed/majie/128/128",
    photo: "https://picsum.photos/seed/majie/128/128",
    topics: ["开源项目", "技术交流"],
    notes: "老朋友，独立开发者，经常交流技术。",
    merged: true, ch: ["Gmail", "WeChat"],
  }),
  mkContact({
    id: "lp", firstName: "Lisa", lastName: "Park", name: "Lisa Park",
    company: "Figma", title: "Product Designer",
    emails: [{ value: "lisa.park@figma.com", label: "work" }],
    phones: [{ value: "+1 415****8921", label: "work" }],
    stage: "active", health: 81, sc: 81, scC: "#34c759", scL: "活跃", lc: "2天前",
    grp: "active", trd: "up",
    pattern: "太平洋时间上午回复，平均 6h",
    accounts: ["gmail-w", "slack"],
    stageHistory: [{ stage: "explore", date: "2025-09-01" }, { stage: "build", date: "2025-12-01" }, { stage: "active", date: "2026-04-01" }],
    firstContact: "2025-09-01",
    milestones: ["设计系统评审 2026-04"],
    avatar: "https://picsum.photos/seed/lisapark/128/128",
    photo: "https://picsum.photos/seed/lisapark/128/128",
    topics: ["设计系统", "组件库", "Figma plugin"],
    notes: "Figma 设计系统合作，对组件一致性和无障碍要求很高。沟通以英文为主，重要文档走邮件，日常对齐走 Slack。",
    merged: true, ch: ["Gmail", "Slack"],
  }),
  mkContact({
    id: "tc", firstName: "Tom", lastName: "Chen", name: "Tom Chen",
    company: "Sequoia Capital", title: "Investment Partner",
    emails: [{ value: "tom.chen@sequoiacap.com", label: "personal" }],
    phones: [{ value: "+1 650****3344", label: "work" }],
    stage: "build", health: 63, sc: 63, scC: "#ff9500", scL: "需跟进", lc: "10天前",
    grp: "risk", trd: "stable",
    pattern: "回复周期 3-5 天，偏好简洁数据",
    accounts: ["gmail-p"],
    stageHistory: [{ stage: "explore", date: "2026-02-01" }, { stage: "build", date: "2026-05-01" }],
    firstContact: "2026-02-01",
    avatar: "https://picsum.photos/seed/tomchen/128/128",
    photo: "https://picsum.photos/seed/tomchen/128/128",
    topics: ["融资", "商业化", "市场数据"],
    notes: "红杉投资人，关注 SendPalm 的商业化路径。需要定期同步关键指标，不要发太长邮件。",
    merged: true, ch: ["Gmail"],
  }),
  mkContact({
    id: "sp", firstName: "SendPalm", lastName: "Support", name: "SendPalm Support",
    company: "SendPalm",
    emails: [{ value: "support@sendpalm.com", label: "work" }],
    phones: [],
    stage: "explore", health: 0, sc: 0, scC: "#8e8e93", scL: "", lc: "昨天",
    pattern: "自动工单 + 人工跟进",
    accounts: ["gmail-w"],
    firstContact: "2025-01-01",
    avatar: "https://picsum.photos/seed/sendpalmsupport/128/128",
    photo: "https://picsum.photos/seed/sendpalmsupport/128/128",
    notes: "产品客服工单系统。",
    defaultBucket: "paperTrail", ch: ["Gmail"],
  }),
  mkContact({
    id: "gh", firstName: "GitHub", lastName: "", name: "GitHub",
    company: "GitHub",
    emails: [{ value: "notifications@github.com", label: "work" }],
    phones: [],
    stage: "explore", health: 0, sc: 0, scC: "#8e8e93", scL: "", lc: "今天",
    pattern: "代码审查与仓库通知",
    accounts: ["gmail-w"],
    firstContact: "2020-01-01",
    avatar: "https://picsum.photos/seed/githubnotifications/128/128",
    photo: "https://picsum.photos/seed/githubnotifications/128/128",
    notes: "GitHub 仓库通知。",
    defaultBucket: "paperTrail", ch: ["Gmail"],
  }),
  mkContact({
    id: "st", firstName: "Stripe", lastName: "", name: "Stripe",
    company: "Stripe",
    emails: [{ value: "noreply@stripe.com", label: "work" }],
    phones: [],
    stage: "explore", health: 0, sc: 0, scC: "#8e8e93", scL: "", lc: "3天前",
    pattern: "支付与账单通知",
    accounts: ["gmail-w"],
    firstContact: "2024-01-01",
    avatar: "https://picsum.photos/seed/stripebilling/128/128",
    photo: "https://picsum.photos/seed/stripebilling/128/128",
    notes: "Stripe 支付通知。",
    defaultBucket: "paperTrail", ch: ["Gmail"],
  }),
  mkContact({
    id: "mi", firstName: "米商城", lastName: "小", name: "小米商城",
    company: "小米",
    emails: [{ value: "order@mi.com", label: "personal" }],
    phones: [],
    stage: "explore", health: 0, sc: 0, scC: "#8e8e93", scL: "", lc: "5天前",
    pattern: "订单与物流通知",
    accounts: ["gmail-p"],
    firstContact: "2023-01-01",
    avatar: "https://picsum.photos/seed/miorders/128/128",
    photo: "https://picsum.photos/seed/miorders/128/128",
    notes: "电商订单通知。",
    defaultBucket: "paperTrail", ch: ["Gmail"],
  }),
  mkContact({
    id: "mom", firstName: "妈", lastName: "妈", name: "妈妈",
    company: "",
    title: "",
    emails: [],
    phones: [{ value: "+86 139****0001", label: "work" }],
    stage: "maintain", health: 0, sc: 0, scC: "#34c759", scL: "活跃", lc: "昨天",
    grp: "active", trd: "stable",
    pattern: "日常问候",
    accounts: ["wechat"],
    firstContact: "2010-01-01",
    avatar: "https://picsum.photos/seed/momchat/128/128",
    photo: "https://picsum.photos/seed/momchat/128/128",
    topics: ["家庭"],
    notes: "家庭群和个人消息。",
    merged: true, ch: ["WeChat"],
  }),
  mkContact({
    id: "rec", firstName: "猎头", lastName: "王", name: "王猎头",
    company: "猎聘网", title: "高级猎头顾问",
    emails: [{ value: "wang.hunter@liepin.com", label: "personal" }],
    phones: [{ value: "+86 138****7777", label: "work" }],
    stage: "explore", health: 0, sc: 0, scC: "#8e8e93", scL: "", lc: "2周前",
    pattern: "不定期职位推荐",
    accounts: ["gmail-p"],
    firstContact: "2025-08-01",
    avatar: "https://picsum.photos/seed/wanghunter/128/128",
    photo: "https://picsum.photos/seed/wanghunter/128/128",
    notes: "猎头推荐，通常直接进 Records。",
    defaultBucket: "feed", ch: ["Gmail"],
  }),
  mkContact({
    id: "nw2", firstName: "Lenny's", lastName: "Newsletter", name: "Lenny's Newsletter",
    company: "Lenny Rachitsky",
    emails: [{ value: "lenny@lennysnewsletter.com", label: "personal" }],
    phones: [],
    stage: "explore", health: 0, sc: 0, scC: "#8e8e93", scL: "", lc: "4天前",
    pattern: "每周产品与管理深度长文",
    accounts: ["gmail-p"],
    firstContact: "2024-03-01",
    avatar: "https://picsum.photos/seed/lennysnewsletter/128/128",
    photo: "https://picsum.photos/seed/lennysnewsletter/128/128",
    notes: "产品订阅通讯。",
    defaultBucket: "feed", ch: ["Gmail"],
  }),
  mkContact({
    id: "unk1", firstName: "新锐", lastName: "李", name: "李新锐",
    company: "未知公司", title: "商务拓展",
    emails: [{ value: "lixinrui@example.com", label: "work" }],
    phones: [],
    stage: "explore", health: 0, sc: 0, scC: "#8e8e93", scL: "", lc: "今天",
    accounts: ["gmail-w"],
    firstContact: "2026-07-20",
    notes: "",
    avatar: "",
    photo: "",
    firstSeen: true, screened: false,
  }),
  mkContact({
    id: "unk2", firstName: "Product", lastName: "Hunt", name: "Product Hunt",
    company: "Product Hunt",
    emails: [{ value: "noreply@producthunt.com", label: "work" }],
    phones: [],
    stage: "explore", health: 0, sc: 0, scC: "#8e8e93", scL: "", lc: "昨天",
    accounts: ["gmail-w"],
    firstContact: "2026-07-18",
    notes: "",
    avatar: "",
    photo: "",
    firstSeen: true, screened: false,
  }),
];

/* Messages — derived from prototype. We'll seed a representative subset. */
export const DEMO_MESSAGES: Message[] = [
  // 张磊 — Q4 合同
  {
    id: "m1", pid: "zl", subj: "Q4 合同付款条款确认", prev: "Hi Edwin，附件是调整后的付款条款 (30-40-30)，请你过目…",
    body: "Hi Edwin，附件是调整后的付款条款 (30-40-30)，请你过目。如果没问题的话，下周一安排签署。\n\n另外三个交付物的验收标准需要提前对齐，附件 2 是我整理的 checklist。",
    tm: "今天 09:42", st: new Date(Date.now() - 2 * 3600_000).toISOString(), ac: "gmail-w",
    bucket: "imbox", unread: true, labels: [], attachments: ["f1", "f2"], trackers: ["utm_source=mail.zhanglei"],
    to: "edwin@sendpalm.com",
  },
  {
    id: "m2", pid: "zl", subj: "Re: 验收标准讨论", prev: "30-40-30 没问题，对附件 2 有一些建议…",
    body: "30-40-30 没问题。对附件 2 有一些建议：交付物 D2 和 D3 的验收窗口能否再缩短一周？",
    tm: "昨天 17:14", st: new Date(Date.now() - 26 * 3600_000).toISOString(), ac: "gmail-w",
    bucket: "imbox", unread: false, labels: [], attachments: [],
  },
  {
    id: "m3", pid: "zl", subj: "Q2 评审会议纪要", prev: "会议要点：Q2 整体进度正常，付款节奏…",
    body: "会议要点：Q2 整体进度正常，付款节奏按 30-30-40 已完成两期。Q3 重点是合同条款对齐。",
    tm: "上周二", st: new Date(Date.now() - 7 * 86400_000).toISOString(), ac: "gmail-w",
    bucket: "imbox", unread: false, labels: [], attachments: [],
  },
  // 陈欣 — Q4 规划
  {
    id: "m4", pid: "cx", subj: "Q4 规划对齐", prev: "Edwin，Q4 规划基本对齐，整合阶段需要…",
    body: "Edwin，Q4 规划基本对齐，整合阶段需要技术评估前置两周。请帮我安排一次技术评审。",
    tm: "今天 11:22", st: new Date(Date.now() - 1 * 3600_000).toISOString(), ac: "gmail-w",
    bucket: "imbox", unread: true, labels: [], attachments: [],
  },
  {
    id: "m5", pid: "cx", subj: "API 升级时间表", prev: "API v3 升级计划已出，预计两周内…",
    body: "API v3 升级计划已出，预计两周内完成。需要你这边确认兼容性窗口。",
    tm: "周一", st: new Date(Date.now() - 3 * 86400_000).toISOString(), ac: "gmail-w",
    bucket: "imbox", unread: false, labels: [], attachments: ["f3"],
  },
  // 王洋 — Q4 提案 (cold)
  {
    id: "m6", pid: "wy", subj: "Re: Q4 提案", prev: "我们内部还在评估预算，请稍候…",
    body: "我们内部还在评估预算，请稍候。月底前给反馈。",
    tm: "上周三", st: new Date(Date.now() - 8 * 86400_000).toISOString(), ac: "gmail-p",
    bucket: "imbox", unread: false, labels: [], attachments: [],
  },
  // 李晨 — AI 方案 (cold)
  {
    id: "m7", pid: "lc", subj: "二期立项推进", prev: "二期立项中，最近忙，待评估…",
    body: "二期立项中，最近忙，待评估。建议 2 周后再发一份 AI 行业洞察。",
    tm: "两周前", st: new Date(Date.now() - 14 * 86400_000).toISOString(), ac: "gmail-w",
    bucket: "imbox", unread: false, labels: [], attachments: [],
    bubbleUpAt: new Date(Date.now() + 14 * 86400_000).toISOString(),
  },
  // 孙静 — 项目部署
  {
    id: "m8", pid: "sj", subj: "Alpha 部署 review", prev: "周五部署前需 review 测试计划…",
    body: "周五部署前需 review 测试计划。已发到 #alpha 频道，请确认。",
    tm: "今天 14:50", st: new Date(Date.now() - 3 * 3600_000).toISOString(), ac: "slack",
    bucket: "imbox", unread: true, labels: [], attachments: [],
  },
  // 杨雨 — 联名活动
  {
    id: "m9", pid: "yy", subj: "联名活动方案 v2", prev: "创意方向 OK，预算需要再压…",
    body: "创意方向 OK，预算需要再压一压。能否给一份更轻量级的资源方案？",
    tm: "周一", st: new Date(Date.now() - 3 * 86400_000).toISOString(), ac: "gmail-w",
    bucket: "imbox", unread: false, labels: [], attachments: ["f4"],
  },
  // 谢明 — Q3 评审
  {
    id: "m10", pid: "xm", subj: "明天评审会资料", prev: "Q3 供应链评估整体 A-，附 PPT…",
    body: "Q3 供应链评估整体 A-，附 PPT。明天 14:00 评审。",
    tm: "昨天 18:30", st: new Date(Date.now() - 18 * 3600_000).toISOString(), ac: "gmail-w",
    bucket: "imbox", unread: true, labels: [], attachments: ["f5"],
  },
  // 刘华 — 二期 (cold)
  {
    id: "m11", pid: "lh", subj: "二期预算进度", prev: "预算流程中，下月初有结果…",
    body: "预算流程中，下月初有结果。请不要频繁催促。",
    tm: "上周", st: new Date(Date.now() - 10 * 86400_000).toISOString(), ac: "gmail-p",
    bucket: "imbox", unread: false, labels: [], attachments: [],
  },
  // 赵薇 — Q3 活动
  {
    id: "m12", pid: "zw", subj: "Q3 活动排期", prev: "设计资源下周三到位，文案还需两天…",
    body: "Q3 活动排期节奏 OK。设计资源下周三到位，文案还需两天。下周一过终稿。",
    tm: "昨天", st: new Date(Date.now() - 22 * 3600_000).toISOString(), ac: "gmail-w",
    bucket: "imbox", unread: false, labels: [], attachments: [],
  },
  // Newsletters (feed)
  {
    id: "m13", pid: "nw", subj: "Frontend Weekly #247", prev: "本期主题：CSS Grid 的实战技巧…",
    body: "本期主题：CSS Grid 的实战技巧。包括 auto-fit、subgrid 和容器查询的深度对比。",
    tm: "昨天", st: new Date(Date.now() - 22 * 3600_000).toISOString(), ac: "gmail-p",
    bucket: "feed", unread: false, labels: [], attachments: [],
  },
  {
    id: "m14", pid: "nw2", subj: "Lenny's Newsletter: Growth metrics", prev: "如何衡量产品增长：每周指标…",
    body: "如何衡量产品增长：每周指标的取舍。增长曲线 vs 留存曲线。",
    tm: "4天前", st: new Date(Date.now() - 4 * 86400_000).toISOString(), ac: "gmail-p",
    bucket: "feed", unread: false, labels: [], attachments: [],
  },
  // Records — receipts
  {
    id: "m15", pid: "aws", subj: "AWS 月度账单", prev: "本月 AWS 费用 $342.18…",
    body: "本月 AWS 费用 $342.18，明细见附件。",
    tm: "2天前", st: new Date(Date.now() - 2 * 86400_000).toISOString(), ac: "gmail-w",
    bucket: "paperTrail", unread: false, labels: [], attachments: [],
  },
  {
    id: "m16", pid: "gh", subj: "[GitHub] PR #247 合并", prev: "PR #247 已合并到 main…",
    body: "PR #247 已合并到 main。",
    tm: "今天 10:15", st: new Date(Date.now() - 5 * 3600_000).toISOString(), ac: "gmail-w",
    bucket: "paperTrail", unread: false, labels: [], attachments: [],
  },
  {
    id: "m17", pid: "st", subj: "Stripe 收款通知", prev: "收到 $5000 USD from…",
    body: "收到 $5000 USD from customer. Stripe 收款通知。",
    tm: "3天前", st: new Date(Date.now() - 3 * 86400_000).toISOString(), ac: "gmail-w",
    bucket: "paperTrail", unread: false, labels: [], attachments: [],
  },
  {
    id: "m18", pid: "mi", subj: "小米订单 #8821 已发货", prev: "您的订单已发货…",
    body: "您的订单 #8821 已发货，预计 3 天送达。",
    tm: "5天前", st: new Date(Date.now() - 5 * 86400_000).toISOString(), ac: "gmail-p",
    bucket: "paperTrail", unread: false, labels: [], attachments: [],
  },
  // Screener
  {
    id: "m19", pid: "unk1", subj: "商务拓展合作咨询", prev: "您好，我们公司提供……",
    body: "您好，我们公司提供商务拓展合作咨询……",
    tm: "今天 08:00", st: new Date(Date.now() - 7 * 3600_000).toISOString(), ac: "gmail-w",
    bucket: "imbox", unread: true, labels: [], attachments: [],
  },
  {
    id: "m20", pid: "unk2", subj: "You've been featured on Product Hunt", prev: "Congrats! Your product has been…",
    body: "Congrats! Your product has been featured on Product Hunt.",
    tm: "昨天", st: new Date(Date.now() - 22 * 3600_000).toISOString(), ac: "gmail-w",
    bucket: "imbox", unread: true, labels: [], attachments: [],
  },
];

export const DEMO_FILES: FileItem[] = [
  {
    id: "f1", pid: "zl", name: "Q4-付款条款-30-40-30.pdf", type: "pdf", mime: "application/pdf",
    size: 245_000, st: new Date(Date.now() - 2 * 3600_000).toISOString(),
    content: "# Q4 付款条款\n\n首期：30%\n中期：40%\n尾期：30%",
  },
  {
    id: "f2", pid: "zl", name: "交付物-checklist.md", type: "doc", mime: "text/markdown",
    size: 8_500, st: new Date(Date.now() - 2 * 3600_000).toISOString(),
    md: "# 交付物 Checklist\n\n- [ ] D1 设计稿\n- [ ] D2 API 文档\n- [ ] D3 部署文档",
  },
  {
    id: "f3", pid: "cx", name: "api-v3-upgrade.md", type: "doc", mime: "text/markdown",
    size: 12_000, st: new Date(Date.now() - 3 * 86400_000).toISOString(),
    md: "# API v3 Upgrade Plan\n\n## Timeline\n- Week 1: Spec freeze\n- Week 2: Beta",
  },
  {
    id: "f4", pid: "yy", name: "联名活动方案v2.pdf", type: "pdf", mime: "application/pdf",
    size: 1_800_000, st: new Date(Date.now() - 3 * 86400_000).toISOString(),
  },
  {
    id: "f5", pid: "xm", name: "Q3-供应链评估.pptx", type: "doc", mime: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    size: 3_200_000, st: new Date(Date.now() - 18 * 3600_000).toISOString(),
  },
];

export const DEMO_EVENTS: CalendarEvent[] = [
  {
    id: "ev1", title: "Q2 评审会议", dt: new Date(Date.now() + 2 * 86400_000).toISOString(), tm: "14:00",
    dur: 60, pids: ["zl", "xm"], color: "#0A8F63", location: "会议室 A",
    agenda: [
      { id: "a1", body: "Q2 进度回顾" },
      { id: "a2", body: "Q3 合同条款对齐" },
    ],
    notes: "",
    brief: "Q2 整体进度正常。Q3 重点是合同条款对齐，付款节奏按 30-30-40。",
    actionItems: [
      { id: "ai1", title: "出 Q3 合同初稿", owner: "zl", done: false },
      { id: "ai2", title: "整理 D2/D3 验收标准", owner: "zl", done: false },
    ],
    materials: [],
  },
  {
    id: "ev2", title: "张磊 — Q3 合同推进", dt: new Date(Date.now() + 5 * 86400_000).toISOString(), tm: "10:00",
    dur: 30, pids: ["zl"], color: "#34c759", videoLink: "https://meet.example.com/abc",
    agenda: [{ id: "a3", body: "Q3 合同条款过会" }],
    notes: "",
    brief: "合同条款对齐：30-40-30 付款节奏，验收窗口再压缩。",
    actionItems: [],
    materials: [{ fileId: "f1" }],
  },
  {
    id: "ev3", title: "谢明 — Q3 评审", dt: new Date(Date.now() + 1 * 86400_000).toISOString(), tm: "14:00",
    dur: 90, pids: ["xm"], color: "#5ac8fa", location: "腾讯会议",
    agenda: [{ id: "a4", body: "Q3 评估报告" }, { id: "a5", body: "Q4 计划" }],
    notes: "",
    brief: "Q3 整体 A-，重点关注小问题项。",
    actionItems: [],
    materials: [{ fileId: "f5" }],
  },
  {
    id: "ev4", title: "孙静 — Alpha 部署 review", dt: new Date(Date.now() + 3 * 86400_000).toISOString(), tm: "16:00",
    dur: 45, pids: ["sj"], color: "#af52de", videoLink: "https://meet.example.com/alpha",
    agenda: [{ id: "a6", body: "测试计划过审" }],
    notes: "",
    brief: "周五部署前的最后 review。",
    actionItems: [],
    materials: [],
  },
];

export const DEMO_TASKS: Task[] = [
  { id: "t1", title: "回复张磊 Q4 付款条款", status: "todo", priority: "high", relatedContactId: "zl", createdAt: new Date(Date.now() - 1 * 86400_000).toISOString(), due: new Date(Date.now() + 1 * 86400_000).toISOString(), notes: "" },
  { id: "t2", title: "准备 Q3 评审 PPT", status: "doing", priority: "high", relatedContactId: "xm", relatedEventId: "ev3", createdAt: new Date(Date.now() - 2 * 86400_000).toISOString(), due: new Date(Date.now() + 1 * 86400_000).toISOString(), notes: "" },
  { id: "t3", title: "给李晨发 AI 行业洞察", status: "todo", priority: "normal", relatedContactId: "lc", createdAt: new Date(Date.now() - 3 * 86400_000).toISOString(), due: new Date(Date.now() + 14 * 86400_000).toISOString(), notes: "不要直接推销" },
  { id: "t4", title: "跟进王洋 Q4 提案", status: "todo", priority: "high", relatedContactId: "wy", createdAt: new Date(Date.now() - 7 * 86400_000).toISOString(), due: new Date(Date.now() + 2 * 86400_000).toISOString(), notes: "" },
];

export const DEMO_DRAFTS: Draft[] = [
  { id: "dr1", recipient: "zhaowei@163.com", subject: "Re: Q3 活动排期", body: "薇姐好，\n\n收到排期。设计资源下周三到位，文案还有两天...", lastEdited: new Date(Date.now() - 2 * 86400_000).toISOString(), status: "edited", accountId: "gmail-w" },
  { id: "dr2", recipient: "support@sendpalm.com", subject: "Re: 工单 #1024", body: "Hi Team,\n\n针对客户反馈...", lastEdited: new Date(Date.now() - 4 * 3600_000).toISOString(), status: "pending", accountId: "gmail-w" },
];

export const DEMO_SNIPPETS: Snippet[] = [
  { id: "sn1", label: "感谢邮件", body: "Hi {{name}},\n\n感谢你今天的沟通，重点我整理如下：\n\n1. ...\n\n下一步我们会在 ... 给到反馈。\n\nBest,\nEdwin", shortcut: "thanks" },
  { id: "sn2", label: "会议邀请", body: "Hi {{name}},\n\n想约你 {{day}} {{time}} 讨论 {{topic}}，时长 30 分钟。\n\n如不方便请回复其他时段。\n\nBest,\nEdwin", shortcut: "meet" },
  { id: "sn3", label: "会议后跟进", body: "Hi {{name}},\n\n感谢今天的会议，核心要点：\n\n- ...\n\n下一步：...\n\nBest,\nEdwin", shortcut: "followup" },
];

export const DEMO_STICKIES: Sticky[] = [];
export const DEMO_CONTACT_NOTES: ContactNote[] = [];
export const DEMO_CLIPS: Clip[] = [];

export const DEMO_FOLLOW_UPS: FollowUp[] = [
  { id: "fu1", msgId: "m6", dueAt: new Date(Date.now() + 2 * 86400_000).toISOString(), status: "pending", note: "王洋月底前给反馈" },
  { id: "fu2", msgId: "m11", dueAt: new Date(Date.now() + 7 * 86400_000).toISOString(), status: "pending", note: "刘华下月初有结果" },
];

export const DEMO_SCHEDULED_SENDS: ScheduledSend[] = [
  { id: "ss1", draftId: "dr1", accountId: "gmail-w", scheduledAt: new Date(Date.now() + 2 * 86400_000).toISOString(), status: "scheduled" },
];

export const DEMO_LABELS: Label[] = [
  { id: "l1", name: "Important", color: "#ff3b30" },
  { id: "l2", name: "Follow up", color: "#ff9500" },
  { id: "l3", name: "Work", color: "#5522fa" },
  { id: "l4", name: "Personal", color: "#299850" },
  { id: "l5", name: "Waiting", color: "#5ac8fa" },
];

export const DEMO_SHORTCUTS: Shortcut[] = [
  { id: "s1", combo: "⌘1", label: "Gate", action: "view.gate", editable: true },
  { id: "s2", combo: "⌘2", label: "Imbox", action: "view.imbox", editable: true },
  { id: "s3", combo: "⌘3", label: "Stream", action: "view.feed", editable: true },
  { id: "s4", combo: "⌘4", label: "Records", action: "view.paperTrail", editable: true },
  { id: "s5", combo: "⌘5", label: "Contacts", action: "view.contacts", editable: true },
  { id: "s6", combo: "⌘6", label: "Calendar", action: "view.calendar", editable: true },
  { id: "s7", combo: "⌘7", label: "Files", action: "view.files", editable: true },
  { id: "s8", combo: "⌘N", label: "Compose", action: "compose.new", editable: true },
  { id: "s9", combo: "⌘K", label: "Command palette", action: "command.palette", editable: true },
  { id: "s10", combo: "l", label: "Reply Later", action: "msg.replyLater", editable: true },
  { id: "s11", combo: "a", label: "Set Aside", action: "msg.setAside", editable: true },
  { id: "s12", combo: "z", label: "Bubble Up", action: "msg.bubbleUp", editable: true },
  { id: "s13", combo: "?", label: "Help", action: "help.show", editable: true },
];

export const DEMO_BUNDLE_CONFIGS: BundleConfig[] = [
  { contactId: "zl", enabled: true, label: "张磊" },
  { contactId: "cx", enabled: true, label: "陈欣" },
];

export const DEMO_NOTIFICATIONS: Notification[] = [
  { id: "n1", type: "relationship", title: "王洋已 45 天未联系", body: "建议发送问候重新激活", ref: { type: "contact", id: "wy" }, read: false, createdAt: new Date(Date.now() - 4 * 3600_000).toISOString() },
  { id: "n2", type: "followup", title: "2 条跟进待处理", body: "王洋月底前、刘华下月初有反馈", read: false, createdAt: new Date(Date.now() - 8 * 3600_000).toISOString() },
  { id: "n3", type: "draft", title: "2 份草稿待审批", body: "Agent 草稿和编辑中草稿", read: true, createdAt: new Date(Date.now() - 26 * 3600_000).toISOString() },
  { id: "n4", type: "agent", title: "会议简报已生成", body: "Q2 评审会议简报已就绪", ref: { type: "event", id: "ev1" }, read: true, createdAt: new Date(Date.now() - 2 * 86400_000).toISOString() },
  { id: "n5", type: "surfaced", title: "李晨回浮到 Imbox", body: "二期立项提醒已触发", ref: { type: "contact", id: "lc" }, read: true, createdAt: new Date(Date.now() - 3 * 86400_000).toISOString() },
];

export const DEMO_AGENT_SESSIONS: AgentSession[] = [
  { id: "as1", kind: "contact", title: "张磊 — Q3 合同推进", context: { type: "contact", ref: "zl" }, createdAt: new Date(Date.now() - 1 * 86400_000).toISOString() },
  { id: "as2", kind: "event", title: "Q2 评审会议简报", context: { type: "event", ref: "ev1" }, createdAt: new Date(Date.now() - 2 * 86400_000).toISOString() },
];

export const DEMO_AGENT_TASKS: AgentTask[] = [
  {
    id: "at1", sessionId: "as1", title: "起草 Q3 合同推进邮件",
    description: "基于最近 5 封邮件起草回复，引用 30-40-30 付款节奏和验收标准。",
    status: "done",
    steps: [
      { id: "at1s1", label: "汇总最近邮件", done: true },
      { id: "at1s2", label: "提炼关键议题", done: true },
      { id: "at1s3", label: "起草回复", done: true },
      { id: "at1s4", label: "等待审批", done: true },
    ],
    confidence: 92,
    trigger: "收到张磊 Q4 付款条款邮件",
    createdAt: new Date(Date.now() - 1 * 86400_000).toISOString(),
  },
  {
    id: "at2", sessionId: "as2", title: "生成 Q2 评审会议简报",
    description: "基于参会人近 30 天邮件生成 5 段简报。",
    status: "doing",
    steps: [
      { id: "at2s1", label: "收集邮件", done: true },
      { id: "at2s2", label: "提炼主题", done: true },
      { id: "at2s3", label: "生成简报", done: false },
    ],
    etaMs: 12_000,
    confidence: 88,
    trigger: "Q2 评审会议前 2 天",
    createdAt: new Date(Date.now() - 2 * 86400_000).toISOString(),
  },
];

export const DEMO_AGENT_DRAFTS: AgentDraft[] = [
  {
    id: "ad1", sessionId: "as1",
    recipient: "zhanglei@huawei.com",
    subject: "Re: Q4 合同付款条款确认",
    body: "Hi 张磊，\n\n收到付款条款 (30-40-30)，整体没问题。\n\n附件 2 的 D2/D3 验收窗口我们建议再压缩一周，下周一前给具体方案。\n\nBest,\nEdwin",
    status: "pending",
    createdAt: new Date(Date.now() - 1 * 86400_000).toISOString(),
  },
];