/** In-memory SQL database for browser-mode testing.
 *
 * Replaces the no-op StubDb in `src/stores/data.ts` when the app runs outside
 * Tauri (e.g. `pnpm dev` and Playwright). It parses the subset of SQLite used
 * by the frontend data layer and keeps state in plain JS objects, so E2E tests
 * can seed contacts/messages/events through the real UI and observe the
 * resulting UI changes.
 *
 * Scope is intentionally limited to the SQL generated by `src/stores/data.ts`.
 */

type Row = Record<string, unknown>;
type Table = Row[];

interface QueryResult {
  rowsAffected: number;
  lastInsertId?: number;
}

const tables: Record<string, Table> = {};

function getTable(name: string): Table {
  const key = name.toLowerCase();
  if (!tables[key]) tables[key] = [];
  return tables[key];
}

function clearAll(): void {
  for (const key of Object.keys(tables)) {
    tables[key] = [];
  }
}

/* ── Tokenizer ─────────────────────────────────────────── */

type Token =
  | { kind: "id"; value: string }
  | { kind: "num"; value: number }
  | { kind: "str"; value: string }
  | { kind: "op"; value: string }
  | { kind: "sym"; value: string };

function charAt(sql: string, i: number): string | undefined {
  return sql[i];
}

function tokenize(sql: string): Token[] {
  const tokens: Token[] = [];
  let i = 0;
  while (i < sql.length) {
    const c = charAt(sql, i);
    if (!c) break;
    if (/\s/.test(c)) {
      i++;
      continue;
    }
    if (c === "'" || c === '"') {
      let s = "";
      const quote = c;
      i++;
      while (i < sql.length) {
        const ch = charAt(sql, i);
        if (ch === quote) {
          const nextCh = charAt(sql, i + 1);
          if (nextCh === quote) {
            s += quote;
            i += 2;
          } else {
            i++;
            break;
          }
        } else if (ch === undefined) {
          break;
        } else {
          s += ch;
          i++;
        }
      }
      tokens.push({ kind: "str", value: s });
      continue;
    }
    if (/[a-zA-Z_]/.test(c)) {
      let s = "";
      while (i < sql.length) {
        const ch = charAt(sql, i);
        if (ch && /[a-zA-Z0-9_]/.test(ch)) {
          s += ch;
          i++;
        } else {
          break;
        }
      }
      tokens.push({ kind: "id", value: s });
      continue;
    }
    if (
      /[0-9]/.test(c) ||
      (c === "-" && /[0-9]/.test(charAt(sql, i + 1) ?? ""))
    ) {
      let s = "";
      let hasDot = false;
      if (c === "-") {
        s += c;
        i++;
      }
      while (i < sql.length) {
        const ch = charAt(sql, i);
        if (ch && /[0-9]/.test(ch)) {
          s += ch;
          i++;
        } else if (ch === "." && !hasDot) {
          hasDot = true;
          s += ch;
          i++;
        } else {
          break;
        }
      }
      tokens.push({ kind: "num", value: Number(s) });
      continue;
    }
    if (c === "$" && /[0-9]/.test(charAt(sql, i + 1) ?? "")) {
      let s = "$";
      i++;
      while (i < sql.length) {
        const ch = charAt(sql, i);
        if (ch && /[0-9]/.test(ch)) {
          s += ch;
          i++;
        } else {
          break;
        }
      }
      tokens.push({ kind: "op", value: s });
      continue;
    }
    if (c === "?") {
      tokens.push({ kind: "op", value: "?" });
      i++;
      continue;
    }
    if ("=<>!".includes(c)) {
      let s = c;
      const next = charAt(sql, i + 1);
      if (next && "=<>".includes(next)) {
        s += next;
        i++;
      }
      tokens.push({ kind: "op", value: s });
      i++;
      continue;
    }
    tokens.push({ kind: "sym", value: c });
    i++;
  }
  return tokens;
}

/* ── Helpers ───────────────────────────────────────────── */

function normalizeId(t: Token | undefined): string {
  return t && t.kind === "id" ? t.value.toLowerCase() : "";
}

function resolveValue(
  tokens: Token[],
  start: number,
  bindValues: unknown[],
): { value: unknown; next: number } {
  const t = tokens[start];
  if (!t) return { value: null, next: start };
  if (t.kind === "str" || t.kind === "num") {
    return { value: t.value, next: start + 1 };
  }
  if (t.kind === "op" && t.value.startsWith("$")) {
    const idx = Number(t.value.slice(1)) - 1;
    return { value: bindValues[idx] ?? null, next: start + 1 };
  }
  if (t.kind === "op" && t.value === "?") {
    // MySQL-style placeholder — not used by the frontend, but keep safe.
    return { value: bindValues[0] ?? null, next: start + 1 };
  }
  if (normalizeId(t) === "null") {
    return { value: null, next: start + 1 };
  }
  if (normalizeId(t) === "datetime") {
    // datetime('now')
    const next = tokens[start + 1];
    if (next?.kind === "sym" && next.value === "(") {
      const close = findClosingParen(tokens, start + 1);
      return { value: new Date().toISOString(), next: close + 1 };
    }
  }
  if (normalizeId(t) === "excluded") {
    // SQLite ON CONFLICT syntax: excluded.column references the new row.
    const dot = tokens[start + 1];
    const col = tokens[start + 2];
    if (dot?.kind === "sym" && dot.value === "." && col?.kind === "id") {
      return {
        value: { __excluded: col.value.toLowerCase() },
        next: start + 3,
      };
    }
  }
  return { value: null, next: start + 1 };
}

function findClosingParen(tokens: Token[], openIdx: number): number {
  let depth = 0;
  for (let i = openIdx; i < tokens.length; i++) {
    const t = tokens[i];
    if (!t) continue;
    if (t.kind === "sym" && t.value === "(") depth++;
    if (t.kind === "sym" && t.value === ")") {
      depth--;
      if (depth === 0) return i;
    }
  }
  return tokens.length - 1;
}

function consumeIdList(
  tokens: Token[],
  start: number,
): { cols: string[]; next: number } {
  const cols: string[] = [];
  let i = start;
  while (i < tokens.length) {
    const t = tokens[i];
    if (t?.kind === "id") {
      cols.push(t.value.toLowerCase());
      i++;
    } else if (t?.kind === "sym" && t.value === ",") {
      i++;
    } else {
      break;
    }
  }
  return { cols, next: i };
}

function compareRows(
  a: Row,
  b: Row,
  orderBy: { col: string; desc: boolean }[],
): number {
  for (const { col, desc } of orderBy) {
    const av = a[col];
    const bv = b[col];
    if (av === bv) continue;
    if (av == null && bv != null) return desc ? 1 : -1;
    if (av != null && bv == null) return desc ? -1 : 1;
    const cmp = String(av).localeCompare(String(bv));
    if (cmp !== 0) return desc ? -cmp : cmp;
  }
  return 0;
}

function matchRow(
  row: Row,
  conditions: Condition[],
  _bindValues: unknown[],
): boolean {
  return conditions.every((cond) => {
    const colVal = row[cond.col];
    switch (cond.op) {
      case "=":
        return colVal === cond.value;
      case "!=":
      case "<>":
        return colVal !== cond.value;
      case ">":
        return colVal != null && cond.value != null && colVal > cond.value;
      case "<":
        return colVal != null && cond.value != null && colVal < cond.value;
      case ">=":
        return colVal != null && cond.value != null && colVal >= cond.value;
      case "<=":
        return colVal != null && cond.value != null && colVal <= cond.value;
      case "in":
        return (
          Array.isArray(cond.value) && cond.value.some((v) => v === colVal)
        );
      case "not in":
        return (
          !Array.isArray(cond.value) ||
          !cond.value.some((v) => v === colVal)
        );
      case "match":
        return matchFts(cond.value, row);
      case "is null":
        return colVal == null;
      case "is not null":
        return colVal != null;
      case "json_contains": {
        try {
          const arr = JSON.parse(String(colVal ?? "[]")) as unknown[];
          return Array.isArray(arr) && arr.some((v) => v === cond.value);
        } catch {
          return false;
        }
      }
      default:
        return true;
    }
  });
}

function matchFts(query: unknown, row: Row): boolean {
  const q = String(query ?? "")
    .toLowerCase()
    .trim();
  if (!q) return true;
  const hay = [row.title, row.body].filter(Boolean).join(" ").toLowerCase();
  return q.split(/\s+/).every((term) => hay.includes(term));
}

interface Condition {
  col: string;
  op: string;
  value: unknown;
}

function readColumnName(tokens: Token[], start: number): { name: string; next: number } {
  let i = start;
  let name = "";
  while (i < tokens.length) {
    const t = tokens[i];
    if (t?.kind === "id") {
      name += t.value;
      i++;
      const dot = tokens[i];
      if (dot?.kind === "sym" && dot.value === ".") {
        name += ".";
        i++;
      } else {
        break;
      }
    } else {
      break;
    }
  }
  return { name: name.toLowerCase(), next: i };
}

function stripTableAlias(col: string, alias?: string): string {
  if (!alias) return col;
  const prefix = `${alias}.`;
  return col.startsWith(prefix) ? col.slice(prefix.length) : col;
}

function parseWhere(
  tokens: Token[],
  start: number,
  bindValues: unknown[],
  jsonColumn?: string,
): { conditions: Condition[]; next: number } {
  const conditions: Condition[] = [];
  let i = start;
  while (i < tokens.length) {
    const t = tokens[i];
    if (!t || t.kind !== "id") break;
    const { name: rawCol, next: afterCol } = readColumnName(tokens, i);
    i = afterCol;
    let col = rawCol;

    // IS NULL / IS NOT NULL
    if (normalizeId(tokens[i]) === "is") {
      i++;
      let op = "is null";
      if (normalizeId(tokens[i]) === "not") {
        op = "is not null";
        i++;
      }
      // consume NULL token
      if (normalizeId(tokens[i]) === "null") i++;
      conditions.push({ col, op, value: null });
    } else if (col === "json_each.value" && jsonColumn) {
      const opToken = tokens[i];
      if (!opToken || (opToken.kind !== "op" && opToken.kind !== "sym")) break;
      i++;
      const afterOp = tokens[i];
      if (
        (opToken.value === "!" &&
          afterOp?.kind === "op" &&
          afterOp.value === "=") ||
        (opToken.value === "<" &&
          afterOp?.kind === "op" &&
          afterOp.value === ">")
      ) {
        i++;
      }
      const { value, next } = resolveValue(tokens, i, bindValues);
      conditions.push({ col: jsonColumn, op: "json_contains", value });
      i = next;
    } else {
      const opToken = tokens[i];
      if (!opToken || (opToken.kind !== "op" && opToken.kind !== "sym")) break;
      let op = opToken.value;
      i++;
      const afterOp = tokens[i];
      if (op === "!" && afterOp?.kind === "op" && afterOp.value === "=") {
        op = "!=";
        i++;
      }
      if (op === "<" && afterOp?.kind === "op" && afterOp.value === ">") {
        op = "<>";
        i++;
      }
      if (op === "not" && normalizeId(tokens[i]) === "in") {
        op = "not in";
        i++;
      }
      const afterOp2 = tokens[i];
      if (afterOp2?.kind === "sym" && afterOp2.value === "(") {
        // IN (...) list
        const close = findClosingParen(tokens, i);
        const vals: unknown[] = [];
        let j = i + 1;
        while (j < close) {
          const { value, next } = resolveValue(tokens, j, bindValues);
          vals.push(value);
          j = next;
          const comma = tokens[j];
          if (comma?.kind === "sym" && comma.value === ",") j++;
        }
        conditions.push({
          col,
          op: op === "not in" ? "not in" : "in",
          value: vals,
        });
        i = close + 1;
      } else {
        const { value, next } = resolveValue(tokens, i, bindValues);
        conditions.push({ col, op, value });
        i = next;
      }
    }
    if (normalizeId(tokens[i]) === "and") {
      i++;
    } else {
      break;
    }
  }
  return { conditions, next: i };
}

interface SelectSource {
  kind: "table" | "json_each";
  name?: string;
  alias?: string;
  jsonColumn?: string;
}

function isReservedKeyword(id: string): boolean {
  return ["where", "order", "limit", "group", "having"].includes(id);
}

function parseFromSources(
  tokens: Token[],
  start: number,
): { sources: SelectSource[]; next: number } {
  const sources: SelectSource[] = [];
  let i = start;
  while (i < tokens.length) {
    const t = tokens[i];
    const kw = normalizeId(t);
    if (kw === "where" || kw === "order" || kw === "limit") break;
    if (kw === "json_each") {
      i++; // json_each
      const open = tokens[i];
      if (open?.kind === "sym" && open.value === "(") {
        i++;
        let expr = "";
        while (i < tokens.length) {
          const t2 = tokens[i];
          if (t2?.kind === "sym" && t2.value === ")") break;
          if (t2) expr += t2.value;
          i++;
        }
        const close = tokens[i];
        if (close?.kind === "sym" && close.value === ")") i++;
        const jsonColumn = expr.split(".").pop()?.toLowerCase() ?? expr.toLowerCase();
        sources.push({ kind: "json_each", jsonColumn });
      }
    } else if (t?.kind === "id") {
      const name = t.value.toLowerCase();
      i++;
      const next = tokens[i];
      let alias: string | undefined;
      if (next?.kind === "id" && !isReservedKeyword(next.value.toLowerCase())) {
        alias = next.value.toLowerCase();
        i++;
      }
      sources.push({ kind: "table", name, alias });
    } else {
      i++;
    }
  }
  return { sources, next: i };
}

/* ── SELECT ────────────────────────────────────────────── */

function runSelect(sql: string, bindValues: unknown[]): Row[] {
  const tokens = tokenize(sql);
  let i = 0;
  if (normalizeId(tokens[i]) !== "select") return [];
  i++;

  // Columns
  const columns: string[] = [];
  let allColumns = false;
  while (i < tokens.length && normalizeId(tokens[i]) !== "from") {
    const t = tokens[i];
    if (t?.kind === "sym" && t.value === "*") {
      allColumns = true;
    } else if (t?.kind === "id") {
      const dot = tokens[i + 1];
      const afterDot = tokens[i + 2];
      if (
        dot?.kind === "sym" &&
        dot.value === "." &&
        afterDot?.kind === "sym" &&
        afterDot.value === "*"
      ) {
        allColumns = true;
        i += 2;
      } else {
        columns.push(t.value.toLowerCase());
      }
    }
    i++;
  }

  if (normalizeId(tokens[i]) !== "from") return [];
  i++;

  const fromSources = parseFromSources(tokens, i);
  i = fromSources.next;
  const mainSource = fromSources.sources.find((s) => s.kind === "table");
  const mainTable = mainSource?.name ?? "";
  const mainAlias = mainSource?.alias;
  const jsonEachColumn = fromSources.sources.find(
    (s) => s.kind === "json_each",
  )?.jsonColumn;
  if (!mainTable) return [];

  let conditions: Condition[] = [];
  let orderBy: { col: string; desc: boolean }[] = [];
  let limit: number | null = null;

  while (i < tokens.length) {
    const t = tokens[i];
    const kw = normalizeId(t);
    if (kw === "where") {
      i++;
      const parsed = parseWhere(tokens, i, bindValues, jsonEachColumn);
      conditions = parsed.conditions.map((c) => ({
        ...c,
        col: stripTableAlias(c.col, mainAlias),
      }));
      i = parsed.next;
    } else if (kw === "order") {
      i++;
      if (normalizeId(tokens[i]) === "by") i++;
      while (i < tokens.length) {
        const { name: rawCol, next: afterCol } = readColumnName(tokens, i);
        i = afterCol;
        const col = stripTableAlias(rawCol, mainAlias);
        if (!col) break;
        let desc = false;
        const dir = normalizeId(tokens[i]);
        if (dir === "desc") {
          desc = true;
          i++;
        } else if (dir === "asc") {
          i++;
        }
        orderBy.push({ col, desc });
        const comma = tokens[i];
        if (comma?.kind === "sym" && comma.value === ",") {
          i++;
        } else {
          break;
        }
      }
    } else if (kw === "limit") {
      i++;
      const { value, next } = resolveValue(tokens, i, bindValues);
      limit = typeof value === "number" ? value : Number(value);
      i = next;
    } else {
      i++;
    }
  }

  const table = getTable(mainTable);
  let rows = table.filter((row) => matchRow(row, conditions, bindValues));
  if (orderBy.length > 0) {
    rows = [...rows].sort((a, b) => compareRows(a, b, orderBy));
  }
  if (limit != null && limit >= 0) {
    rows = rows.slice(0, limit);
  }

  if (columns.some((c) => c.startsWith("count("))) {
    return [{ cnt: rows.length }];
  }

  if (allColumns) return rows;
  return rows.map((row) => {
    const out: Row = {};
    for (const c of columns) out[c] = row[c];
    return out;
  });
}

/* ── INSERT / UPDATE ───────────────────────────────────── */

function parseColumnAssignments(
  tokens: Token[],
  start: number,
  bindValues: unknown[],
): { assignments: { col: string; value: unknown }[]; next: number } {
  const assignments: { col: string; value: unknown }[] = [];
  let i = start;
  while (i < tokens.length) {
    const col = normalizeId(tokens[i]);
    if (!col) break;
    i++;
    const eq = tokens[i];
    if (!(eq?.kind === "op" && eq.value === "=")) break;
    i++;
    const { value, next } = resolveValue(tokens, i, bindValues);
    assignments.push({ col, value });
    i = next;
    const comma = tokens[i];
    if (comma?.kind === "sym" && comma.value === ",") {
      i++;
    } else {
      break;
    }
  }
  return { assignments, next: i };
}

function runInsert(sql: string, bindValues: unknown[]): QueryResult {
  const tokens = tokenize(sql);
  let i = 0;
  if (normalizeId(tokens[i]) !== "insert") return { rowsAffected: 0 };
  i++;
  if (normalizeId(tokens[i]) === "or") i += 2; // INSERT OR REPLACE/IGNORE
  if (normalizeId(tokens[i]) !== "into") return { rowsAffected: 0 };
  i++;
  const tableName = normalizeId(tokens[i]);
  i++;
  if (!tableName) return { rowsAffected: 0 };

  const openParen = tokens[i];
  if (!(openParen?.kind === "sym" && openParen.value === "("))
    return { rowsAffected: 0 };
  i++;
  const { cols, next: afterCols } = consumeIdList(tokens, i);
  i = afterCols;
  const closeParen = tokens[i];
  if (!(closeParen?.kind === "sym" && closeParen.value === ")"))
    return { rowsAffected: 0 };
  i++;

  if (normalizeId(tokens[i]) !== "values") return { rowsAffected: 0 };
  i++;

  let rowsAffected = 0;
  while (
    i < tokens.length &&
    tokens[i]?.kind === "sym" &&
    tokens[i]!.value === "("
  ) {
    const close = findClosingParen(tokens, i);
    const row: Row = {};
    let vi = i + 1;
    let ci = 0;
    while (vi < close) {
      const { value, next } = resolveValue(tokens, vi, bindValues);
      const colName = cols[ci];
      if (colName) row[colName] = value;
      vi = next;
      const comma = tokens[vi];
      if (comma?.kind === "sym" && comma.value === ",") vi++;
      ci++;
    }

    let onConflictUpdates: { col: string }[] | null = null;
    i = close + 1;
    if (
      normalizeId(tokens[i]) === "on" &&
      normalizeId(tokens[i + 1]) === "conflict"
    ) {
      // ON CONFLICT(...) DO UPDATE SET col=excluded.col, ...
      let j = i + 2;
      const conflictOpen = tokens[j];
      if (conflictOpen?.kind === "sym" && conflictOpen.value === "(") {
        j = findClosingParen(tokens, j) + 1;
      }
      if (normalizeId(tokens[j]) === "do") j++;
      if (normalizeId(tokens[j]) === "update") j++;
      if (normalizeId(tokens[j]) === "set") j++;
      const parsed = parseColumnAssignments(tokens, j, bindValues);
      onConflictUpdates = parsed.assignments.map((a) => ({ col: a.col }));
      i = parsed.next;
    }

    const table = getTable(tableName);
    const idCol = "id";
    const existingIdx = table.findIndex((r) => r[idCol] === row[idCol]);
    if (existingIdx >= 0) {
      if (onConflictUpdates) {
        for (const { col } of onConflictUpdates) {
          table[existingIdx]![col] = row[col];
        }
      }
    } else {
      table.push(row);
      rowsAffected++;
    }
  }

  return { rowsAffected };
}

function runUpdate(sql: string, bindValues: unknown[]): QueryResult {
  const tokens = tokenize(sql);
  let i = 0;
  if (normalizeId(tokens[i]) !== "update") return { rowsAffected: 0 };
  i++;
  const tableName = normalizeId(tokens[i]);
  i++;
  if (!tableName) return { rowsAffected: 0 };
  if (normalizeId(tokens[i]) !== "set") return { rowsAffected: 0 };
  i++;

  const { assignments, next } = parseColumnAssignments(tokens, i, bindValues);
  i = next;

  let conditions: Condition[] = [];
  if (normalizeId(tokens[i]) === "where") {
    i++;
    const parsed = parseWhere(tokens, i, bindValues);
    conditions = parsed.conditions;
  }

  const table = getTable(tableName);
  let rowsAffected = 0;
  for (const row of table) {
    if (!matchRow(row, conditions, bindValues)) continue;
    for (const { col, value } of assignments) {
      row[col] = value;
    }
    rowsAffected++;
  }
  return { rowsAffected };
}

function runDelete(sql: string, bindValues: unknown[]): QueryResult {
  const tokens = tokenize(sql);
  let i = 0;
  if (normalizeId(tokens[i]) !== "delete") return { rowsAffected: 0 };
  i++;
  if (normalizeId(tokens[i]) === "from") i++;
  const tableName = normalizeId(tokens[i]);
  i++;
  if (!tableName) return { rowsAffected: 0 };

  let conditions: Condition[] = [];
  if (normalizeId(tokens[i]) === "where") {
    i++;
    const parsed = parseWhere(tokens, i, bindValues);
    conditions = parsed.conditions;
  }

  const table = getTable(tableName);
  if (conditions.length === 0) {
    const n = table.length;
    tables[tableName] = [];
    return { rowsAffected: n };
  }
  const before = table.length;
  tables[tableName] = table.filter(
    (row) => !matchRow(row, conditions, bindValues),
  );
  return { rowsAffected: before - tables[tableName].length };
}

/* ── Public class ──────────────────────────────────────── */

export class MockDb {
  select<T>(query: string, bindValues?: unknown[]): Promise<T> {
    const q = query.trim().toLowerCase();
    if (q.startsWith("select")) {
      return Promise.resolve(runSelect(query, bindValues ?? []) as T);
    }
    return Promise.resolve([] as unknown as T);
  }

  execute(query: string, bindValues?: unknown[]): Promise<QueryResult> {
    const q = query.trim().toLowerCase();
    let result: QueryResult;
    if (q.startsWith("insert")) {
      result = runInsert(query, bindValues ?? []);
    } else if (q.startsWith("update")) {
      result = runUpdate(query, bindValues ?? []);
    } else if (q.startsWith("delete")) {
      result = runDelete(query, bindValues ?? []);
    } else {
      result = { rowsAffected: 0 };
    }
    return Promise.resolve(result);
  }
}

/** Reset every in-memory table. Exposed for E2E tests. */
export function resetMockDb(): void {
  clearAll();
}
